name: Terraform Apply (Prod firewall)

on:
  workflow_dispatch:
    inputs:
      working_directory:
        description: "Terraform working directory"
        required: true
        type: choice
        options: [sonarqube, prometheus, prod]

      aws_access_key:
        description: "AWS Access Key"
        required: true

      aws_secret_key:
        description: "AWS Secret Key"
        required: true

      aws_region:
        description: "AWS Region"
        required: true
        default: "ap-south-1"

      instance_type:
        description: "EC2 instance type"
        required: true
        default: "t3.micro"

      root_volume_type:
        description: "Root volume type"
        required: true
        default: "gp3"

      root_volume_size:
        description: "Root volume size (GB)"
        required: true
        default: "20"

      delete_on_termination:
        description: "Delete volume on termination"
        required: true
        type: boolean
        default: true

      ami_owners:
        description: "AMI owners (comma separated)"
        required: true

      ami_name_pattern:
        description: "AMI name pattern"
        required: true

      ami_virtualization_type:
        description: "AMI virtualization type"
        required: true
        default: "hvm"

      ami_architecture:
        description: "AMI architecture"
        required: true
        default: "x86_64"

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Apply
        working-directory: ./terraform/envs/${{ inputs.working_directory }}
        env:
          TF_VAR_aws_access_key: ${{ inputs.aws_access_key }}
          TF_VAR_aws_secret_key: ${{ inputs.aws_secret_key }}
          TF_VAR_aws_region: ${{ inputs.aws_region }}

          TF_VAR_environment: ${{ inputs.working_directory }}
          TF_VAR_instance_type: ${{ inputs.instance_type }}
          TF_VAR_root_volume_type: ${{ inputs.root_volume_type }}
          TF_VAR_root_volume_size: "${{ inputs.root_volume_size }}"
          TF_VAR_delete_on_termination: "${{ inputs.delete_on_termination }}"

          TF_VAR_ami_owners: '["${{ inputs.ami_owners }}"]'
          TF_VAR_ami_name_pattern: ${{ inputs.ami_name_pattern }}
          TF_VAR_ami_virtualization_type: ${{ inputs.ami_virtualization_type }}
          TF_VAR_ami_architecture: ${{ inputs.ami_architecture }}

          TF_VAR_tags: '{"Project":"ec2","Environment":"${{ inputs.working_directory }}","ManagedBy":"terraform","Owner":"Security-Team"}'

        run: |
          terraform init
          terraform validate
          terraform plan
          terraform apply -auto-approve
